# Generated by Django 4.1.7 on 2023-05-01 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='brands')),
                ('origin', models.CharField(max_length=50)),
                ('manufacturing_date', models.DateField()),
                ('slug', models.SlugField(default='null', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='models')),
                ('launch_date', models.DateField()),
                ('platform', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='null', max_length=150)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhoneReview.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('date_published', models.DateTimeField(auto_now=True)),
                ('model', models.ManyToManyField(to='PhoneReview.model')),
            ],
        ),
    ]
